server:
  port: 9092
eureka:
  client:
    healthcheck:
      enabled: true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  server:
    wait-time-in-ms-when-sync-empty: 3000
spring:
  activemq:
    broker-url: tcp://localhost:61616   
  zipkin:
    baseUrl: ${ZIPKIN_URL:http://localhost:9411/}    
queue:
  boot: customer.event    
memcached.cache:
   servers: 127.0.0.1:11211
   mode: static
   expiration: 30
management:
  security: 
    enabled: false   

