server:
   port:  9091
eureka:
  client:
    healthcheck:
      enabled: true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  server:
    wait-time-in-ms-when-sync-empty: 3000
feign:
    hystrix:
        enabled: true    
spring:
  zipkin: 
    baseUrl: ${ZIPKIN_URL:http://localhost:9411/}
hystrix:
  command:
    Microservice2Service#getCustomers(String):
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000
logging:
  level:
    org.springframework.web.client: TRACE
    org.springframework.http.client: TRACE
    org.springframework.security: DEBUG
security:
  basic:
    enabled: true                   
  oauth2:
    client:
      clientId: my-client-with-secret   
      clientSecret: secret
      accessTokenUri: http://localhost:9094/oauth/token
      userAuthorizationUri: http://localhost:9094/oauth/authorize
management:
  security: 
    enabled: false      
      