server:
  port: 9094
logging:
  level:
    org.springframework.web.client: TRACE
    org.springframework.http.client: TRACE
    org.springframework.security: DEBUG
management:
  security: 
    enabled: false