server:
  port: 10001
management:
  security: 
    enabled: false
spring:
  cloud:
    config: 
      server:
        git:
          uri: https://github.com/fabioseregni/microservices-by-examples/config
        bootstrap: true  
          
